### ISSUE TITLE
Answer page needs to handle when there is no answer data

### ISSUE THREAD

**Issue by maximusunc** [NCATS-Gamma/robokop-rewrite#114]
I keep running into issues where I get an answer back from Messenger, but the actual data fails to get saved. When there's no answer data when I click to view that answer, the page crashes when trying to parse the non-existent json.

Steps to reproduce:
1. Ask a new question from template
2. Choose question WF2 Module 1a : disease to genes to chemi-similar genes.
3. Enter ebola for the disease
4. Ask question

**Comment by alongreyber** [comment]
I'm not able to reproduce this issue. When I ask that question I get a valid answer back. Do you have a different question I could try?

**Comment by alongreyber** [comment]
Do you just want me to add a check if the answer data JSON is valid, or do you want me to debug whatever issue is causing the data to fail being saved? It's a bit unclear from the issue description.

**Comment by maximusunc** [comment]
Yes, we should start with just checking that the answer data is valid. There are at least two places, one when we get an answer back from the ARA, and then when we request it again from Robokache.

**Comment by maximusunc** [comment]
To reproduce, `git checkout 1213a0eab7bf30b10c347a1fec03cc1971de8de0`, which is the commit right before we added back in the axios maxBodyLength limit change, and follow the above steps. This was failing because when the express server was trying to pass the answer through, it is bigger than the default axios limits and failing to send to Robokache.

With that being said, we should still handle when invalid JSON enters the pipeline.

**Comment by maximusunc** [comment]
There was one other worse instance of something like this happening where the page actually crashed. I'll look into finding some reproducible steps.

**Comment by maximusunc** [comment]
> There was one other worse instance of something like this happening where the page actually crashed. I'll look into finding some reproducible steps.

The page crashes on main branch when the answer file doesn't exist, so it looks like this PR will fix that.
