### ISSUE TITLE
Make node normalizer call more consistent

### ISSUE THREAD

**Issue by maximusunc** [NCATS-Gamma/robokop-rewrite#140]
At least when developing, this call seems to fail the most with 502 Bad Gateway errors. It seems to happen the most when hot reloading or making code changes. I check and the actual services are working fine, so I think this is an issue on our end.

**Comment by cbizon** [comment]
There's a POST method that got added recently - might try using that if you are not already

**Comment by maximusunc** [comment]
Thanks, Chris. That simplifies things quite a bit! Unfortunately, the POST method doesn't fix this particular issue.

**Comment by maximusunc** [comment]
This seems to be solved by putting:
`dns: - 1.1.1.1`
in docker-compose.base.yml. We think on Mac the docker VM doesn't have a static DNS, so we need to manually set it. I think this is just a local development issue, and would actually cause a problem in deployment. So for now, I think this change should stay uncommitted.
