### ISSUE TITLE
Convert Robokop to interface with Strider

### ISSUE THREAD

**Issue by alongreyber** [NCATS-Gamma/robokop-rewrite#157]
Robokop needs to be converted to match TRAPI v1.0 to be able to communicate with messenger and strider. Steps required in order to get this done:

- [x] Rename source_id -> subject everywhere in the code
- [x] Rename target_id -> object everywhere in the code
- [x] Rename type -> category wherever we use type for a node type
- [x] Fix templates to match new format
- [x] Rename node curie -> id
- [x] Rename edge category/type -> predicate
- [x] Remove helper functions for graph representation conversions (reasonerToInternal, etc)
- [x] Swap `ara.js` to interface with Strider

**Comment by maximusunc** [comment]
I think this looks good. Make sure you change the question templates as well.

We will need to at least keep the internalToReasoner function because the QuestionGraphView (it's actually react-graph-vis) that requires an array of node and edges.

**Comment by maximusunc** [comment]
#168
