### ISSUE TITLE
Wrong CURIE in tutorial

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop-rewrite#273]
This issue is to report that the question-builder tutorial (https://robokop.renci.org/question-builder/tutorial) includes an incorrect CURIE. Specifically, `UMLS:C003965` needs to be replaced with `PUBCHEM.COMPOUND:15625`. I have fixed the typo in the [G-documentation](https://docs.google.com/document/d/1yfnpLmsAK3Qy2x0ItVl9RSIttfWn2KCK/edit?usp=sharing&ouid=112054006232285231595&rtpof=true&sd=true), but I'm not sure what the most efficient way is to fix it in the UI.

**Comment by Woozl** [comment]
https://github.com/RobokopU24/qgraph/commit/a7256356b81df7f01b3e0523c461c1ff39d8effb
