### ISSUE TITLE
Update parseMessage and error reporting for ingested messages

### ISSUE THREAD

**Issue by maximusunc** [NCATS-Gamma/robokop-rewrite#40]
I tried the Ask ARA functionality with the covidkop response. No results or knowledge_graph were returned and the error message was "Unable to parse message". I think we should change that error to be more descriptive when there are no answers returned. My thinking is that we parse those messages without error and then display an error message in the AnswersetView.

_Originally posted by @alongreyber in https://github.com/NCATS-Gamma/robokop-rewrite/pull/37#discussion_r501756507_

**Comment by maximusunc** [comment]
An answer with no results is completely valid, and probably shouldn't even display an error message. We should show the query graph and an empty results table.

**Comment by alongreyber** [comment]
This is what I am working on fixing right now in #139. Do you want me to merge that and create a separate PR for this issue?

**Comment by maximusunc** [comment]
No. This is completely separate. You shouldn't be working on this right now.

**Comment by maximusunc** [comment]
There are a few issues with the parseMessage function and also how we're reporting errors to the user. It looks like two places need some attention:

- [ ] Simple Viewer message uploads
- [ ] StoredAnswersetViewer and messages we get back from ARAs

The parseMessage function needs to handle a wider range of message types and return descriptive errors, and then the two components that use it need to show the user these errors as well as give the user options for next steps.

I'm going to tackle the simple viewer first and if it turns out to be a lot, I will probably make a separate error reporting issue for the stored answerset viewer.
