### ISSUE TITLE
Separate queryDispatcher into separate service

### ISSUE THREAD

**Issue by alongreyber** [NCATS-Gamma/robokop-rewrite#97]
Currently, queryDispatcher is in the same container that serves the frontend. There are a few disadvantages:

- API calls to an invalid endpoint can't return a 404 error
- No hot reloading is available for queryDispatcher
- Express is serving the HTTP bundle, where we should be using an optimized static HTTP server

Eventually, we should separate queryDispatcher to a separate container.

**Comment by maximusunc** [comment]
Done in #132
